DROP TABLE currencies_en;
CREATE TABLE currencies_en (
    code char(3) CONSTRAINT currency_code PRIMARY KEY ASC,
    id int(1),
    decimals int(1),
    currency varchar(50) CONSTRAINT currency_name UNIQUE,
    countries varbinary(100),
    enabled int(1)
);
INSERT INTO currencies_en VALUES ('AED',784,2,'United Arab Emirates dirham','AE',0);
INSERT INTO currencies_en VALUES ('AFN',971,2,'Afghan afghani','AF',0);
INSERT INTO currencies_en VALUES ('ALL',008,2,'Albanian lek','AL',0);
INSERT INTO currencies_en VALUES ('AMD',051,2,'Armenian dram','AM',0);
INSERT INTO currencies_en VALUES ('ANG',532,2,'Netherlands Antillean guilder',null,0);
INSERT INTO currencies_en VALUES ('AOA',973,2,'Angolan kwanza','AO',0);
INSERT INTO currencies_en VALUES ('ARS',032,2,'Argentine peso','AR',0);
INSERT INTO currencies_en VALUES ('AUD',036,2,'Australian dollar','AU,CX,CC,HM,KI,NR,NF,TV',0);
INSERT INTO currencies_en VALUES ('AWG',533,2,'Aruban florin','AW',0);
INSERT INTO currencies_en VALUES ('AZN',944,2,'Azerbaijani manat','AZ',0);
INSERT INTO currencies_en VALUES ('BAM',977,2,'Bosnia and Herzegovina convertible mark','BA',0);
INSERT INTO currencies_en VALUES ('BBD',052,2,'Barbados dollar','BB',0);
INSERT INTO currencies_en VALUES ('BDT',050,2,'Bangladeshi taka','BD',0);
INSERT INTO currencies_en VALUES ('BGN',975,2,'Bulgarian lev','BG',0);
INSERT INTO currencies_en VALUES ('BHD',048,3,'Bahraini dinar','BH',0);
INSERT INTO currencies_en VALUES ('BIF',108,0,'Burundian franc','BI',0);
INSERT INTO currencies_en VALUES ('BMD',060,2,'Bermudian dollar','BM',0);
INSERT INTO currencies_en VALUES ('BND',096,2,'Brunei dollar','BN,SG',0);
INSERT INTO currencies_en VALUES ('BOB',068,2,'Boliviano','BO',0);
INSERT INTO currencies_en VALUES ('BOV',984,2,'Bolivian Mvdol (funds code)','BO',0);
INSERT INTO currencies_en VALUES ('BRL',986,2,'Brazilian real','BR',0);
INSERT INTO currencies_en VALUES ('BSD',044,2,'Bahamian dollar','BS',0);
INSERT INTO currencies_en VALUES ('BTN',064,2,'Bhutanese ngultrum','BT',0);
INSERT INTO currencies_en VALUES ('BWP',072,2,'Botswana pula','BW',0);
INSERT INTO currencies_en VALUES ('BYR',974,0,'Belarusian ruble','BY',0);
INSERT INTO currencies_en VALUES ('BZD',084,2,'Belize dollar','BZ',0);
INSERT INTO currencies_en VALUES ('CAD',124,2,'Canadian dollar','CA,PM',0);
INSERT INTO currencies_en VALUES ('CDF',976,2,'Congolese franc','CD',0);
INSERT INTO currencies_en VALUES ('CHE',947,2,'WIR Bank Euro (Complementary currency)','CH',0);
INSERT INTO currencies_en VALUES ('CHF',756,2,'Swiss franc','CH,LI',0);
INSERT INTO currencies_en VALUES ('CHW',948,2,'WIR Bank Franc (Complementary currency)','CH',0);
INSERT INTO currencies_en VALUES ('CLF',990,0,'Unidad de Fomento (funds code)','CL',0);
INSERT INTO currencies_en VALUES ('CLP',152,0,'Chilean peso','CL',0);
INSERT INTO currencies_en VALUES ('CNY',156,2,'Renminbi','CN',0);
INSERT INTO currencies_en VALUES ('COP',170,2,'Colombian peso','CO',0);
INSERT INTO currencies_en VALUES ('COU',970,4,'Unidad de Valor Real (funds code)','CO',0);
INSERT INTO currencies_en VALUES ('CRC',188,2,'Costa Rican colon','CR',0);
INSERT INTO currencies_en VALUES ('CUC',931,2,'Cuban convertible peso','CU',0);
INSERT INTO currencies_en VALUES ('CUP',192,2,'Cuban peso','CU',0);
INSERT INTO currencies_en VALUES ('CVE',132,0,'Cape Verde escudo','CV',0);
INSERT INTO currencies_en VALUES ('CZK',203,2,'Czech koruna','CZ',0);
INSERT INTO currencies_en VALUES ('DJF',262,0,'Djiboutian franc','DJ',0);
INSERT INTO currencies_en VALUES ('DKK',208,2,'Danish krone','DK,FO,GL',0);
INSERT INTO currencies_en VALUES ('DOP',214,2,'Dominican peso','DO',0);
INSERT INTO currencies_en VALUES ('DZD',012,2,'Algerian dinar','DZ',0);
INSERT INTO currencies_en VALUES ('EGP',818,2,'Egyptian pound','EG',0);
INSERT INTO currencies_en VALUES ('ERN',232,2,'Eritrean nakfa','ER',0);
INSERT INTO currencies_en VALUES ('ETB',230,2,'Ethiopian birr','ET',0);
INSERT INTO currencies_en VALUES ('EUR',978,2,'Euro','AD,AT,BE,CY,EE,FI,FR,DE,GR,IE,IT,LV,LU,MT,MC,NL,PT,SM,SK,SI,ES,VA',0);
INSERT INTO currencies_en VALUES ('FJD',242,2,'Fiji dollar','FJ',0);
INSERT INTO currencies_en VALUES ('FKP',238,2,'Falkland Islands pound','FK',0);
INSERT INTO currencies_en VALUES ('GBP',826,2,'Pound sterling','GB',0);
INSERT INTO currencies_en VALUES ('GEL',981,2,'Georgian lari','GE',0);
INSERT INTO currencies_en VALUES ('GHS',936,2,'Ghanaian cedi','GH',0);
INSERT INTO currencies_en VALUES ('GIP',292,2,'Gibraltar pound','GI',0);
INSERT INTO currencies_en VALUES ('GMD',270,2,'Gambian dalasi','GM',0);
INSERT INTO currencies_en VALUES ('GNF',324,0,'Guinean franc','GN',0);
INSERT INTO currencies_en VALUES ('GTQ',320,2,'Guatemalan quetzal','GT',0);
INSERT INTO currencies_en VALUES ('GYD',328,2,'Guyanese dollar','GY',0);
INSERT INTO currencies_en VALUES ('HKD',344,2,'Hong Kong dollar','HK,MO',0);
INSERT INTO currencies_en VALUES ('HNL',340,2,'Honduran lempira','HN',0);
INSERT INTO currencies_en VALUES ('HRK',191,2,'Croatian kuna','HR',0);
INSERT INTO currencies_en VALUES ('HTG',332,2,'Haitian gourde','HT',0);
INSERT INTO currencies_en VALUES ('HUF',348,2,'Hungarian forint','HU',0);
INSERT INTO currencies_en VALUES ('IDR',360,2,'Indonesian rupiah','ID',0);
INSERT INTO currencies_en VALUES ('ILS',376,2,'Israeli new shekel','IL',0);
INSERT INTO currencies_en VALUES ('INR',356,2,'Indian rupee','IN',0);
INSERT INTO currencies_en VALUES ('IQD',368,3,'Iraqi dinar','IQ',0);
INSERT INTO currencies_en VALUES ('IRR',364,2,'Iranian rial','IR',0);
INSERT INTO currencies_en VALUES ('ISK',352,0,'Icelandic króna','IS',0);
INSERT INTO currencies_en VALUES ('JMD',388,2,'Jamaican dollar','JM',0);
INSERT INTO currencies_en VALUES ('JOD',400,3,'Jordanian dinar','JO',0);
INSERT INTO currencies_en VALUES ('JPY',392,0,'Japanese yen','JP',0);
INSERT INTO currencies_en VALUES ('KES',404,2,'Kenyan shilling','KE',0);
INSERT INTO currencies_en VALUES ('KGS',417,2,'Kyrgyzstani som','KG',0);
INSERT INTO currencies_en VALUES ('KHR',116,2,'Cambodian riel','KH',0);
INSERT INTO currencies_en VALUES ('KMF',174,0,'Comoro franc','KM',0);
INSERT INTO currencies_en VALUES ('KPW',408,2,'North Korean won','KR',0);
INSERT INTO currencies_en VALUES ('KRW',410,0,'South Korean won','Kp',0);
INSERT INTO currencies_en VALUES ('KWD',414,3,'Kuwaiti dinar','KW',0);
INSERT INTO currencies_en VALUES ('KYD',136,2,'Cayman Islands dollar','KY',0);
INSERT INTO currencies_en VALUES ('KZT',398,2,'Kazakhstani tenge','KZ',0);
INSERT INTO currencies_en VALUES ('LAK',418,2,'Lao kip','LA',0);
INSERT INTO currencies_en VALUES ('LBP',422,2,'Lebanese pound','LB',0);
INSERT INTO currencies_en VALUES ('LKR',144,2,'Sri Lankan rupee','LK',0);
INSERT INTO currencies_en VALUES ('LRD',430,2,'Liberian dollar','LR',0);
INSERT INTO currencies_en VALUES ('LSL',426,2,'Lesotho loti','LS',0);
INSERT INTO currencies_en VALUES ('LTL',440,2,'Lithuanian litas','LT',0);
INSERT INTO currencies_en VALUES ('LYD',434,3,'Libyan dinar','LY',0);
INSERT INTO currencies_en VALUES ('MAD',504,2,'Moroccan dirham','MA',0);
INSERT INTO currencies_en VALUES ('MDL',498,2,'Moldovan leu','MD',0);
INSERT INTO currencies_en VALUES ('MGA',969,2,'Malagasy ariary','MG',0);
INSERT INTO currencies_en VALUES ('MKD',807,2,'Macedonian denar','MK',0);
INSERT INTO currencies_en VALUES ('MMK',104,2,'Myanma kyat','MM',0);
INSERT INTO currencies_en VALUES ('MNT',496,2,'Mongolian tögrög','MN',0);
INSERT INTO currencies_en VALUES ('MOP',446,2,'Macanese pataca','MO',0);
INSERT INTO currencies_en VALUES ('MRO',478,2,'Mauritanian ouguiya','MR',0);
INSERT INTO currencies_en VALUES ('MUR',480,2,'Mauritian rupee','MU',0);
INSERT INTO currencies_en VALUES ('MVR',462,2,'Maldivian rufiyaa','MV',0);
INSERT INTO currencies_en VALUES ('MWK',454,2,'Malawian kwacha','MW',0);
INSERT INTO currencies_en VALUES ('MXN',484,2,'Mexican peso','MX',0);
INSERT INTO currencies_en VALUES ('MXV',979,2,'Mexican Unidad de Inversion','MX',0);
INSERT INTO currencies_en VALUES ('MYR',458,2,'Malaysian ringgit','MY',0);
INSERT INTO currencies_en VALUES ('MZN',943,2,'Mozambican metical','MZ',0);
INSERT INTO currencies_en VALUES ('NAD',516,2,'Namibian dollar','NA',0);
INSERT INTO currencies_en VALUES ('NGN',566,2,'Nigerian naira','NE',0);
INSERT INTO currencies_en VALUES ('NIO',558,2,'Nicaraguan córdoba','NI',0);
INSERT INTO currencies_en VALUES ('NOK',578,2,'Norwegian krone','NO,SJ,BV',0);
INSERT INTO currencies_en VALUES ('NPR',524,2,'Nepalese rupee','NP',0);
INSERT INTO currencies_en VALUES ('NZD',554,2,'New Zealand dollar','CK,NZ,NU,PN,TK',0);
INSERT INTO currencies_en VALUES ('OMR',512,3,'Omani rial','OM',0);
INSERT INTO currencies_en VALUES ('PAB',590,2,'Panamanian balboa','PA',0);
INSERT INTO currencies_en VALUES ('PEN',604,2,'Peruvian nuevo sol','PE',0);
INSERT INTO currencies_en VALUES ('PGK',598,2,'Papua New Guinean kina','PG',0);
INSERT INTO currencies_en VALUES ('PHP',608,2,'Philippine peso','PH',0);
INSERT INTO currencies_en VALUES ('PKR',586,2,'Pakistani rupee','PK',0);
INSERT INTO currencies_en VALUES ('PLN',985,2,'Polish złoty','PL',0);
INSERT INTO currencies_en VALUES ('PYG',600,0,'Paraguayan guaraní','PY',0);
INSERT INTO currencies_en VALUES ('QAR',634,2,'Qatari riyal','QA',0);
INSERT INTO currencies_en VALUES ('RON',946,2,'Romanian Leu','RO',0);
INSERT INTO currencies_en VALUES ('RSD',941,2,'Serbian dinar','',0);
INSERT INTO currencies_en VALUES ('RUB',643,2,'Russian ruble','RU',0);
INSERT INTO currencies_en VALUES ('RWF',646,0,'Rwandan franc','RW',0);
INSERT INTO currencies_en VALUES ('SAR',682,2,'Saudi riyal','SA',0);
INSERT INTO currencies_en VALUES ('SBD',090,2,'Solomon Islands dollar','SB',0);
INSERT INTO currencies_en VALUES ('SCR',690,2,'Seychelles rupee','SC',0);
INSERT INTO currencies_en VALUES ('SDG',938,2,'Sudanese pound','SD',0);
INSERT INTO currencies_en VALUES ('SEK',752,2,'Swedish krona','SE',0);
INSERT INTO currencies_en VALUES ('SGD',702,2,'Singapore dollar','SG,BN',0);
INSERT INTO currencies_en VALUES ('SHP',654,2,'Saint Helena pound','SH',0);
INSERT INTO currencies_en VALUES ('SLL',694,2,'Sierra Leonean leone','SL',0);
INSERT INTO currencies_en VALUES ('SOS',706,2,'Somali shilling','SO',0);
INSERT INTO currencies_en VALUES ('SRD',968,2,'Surinamese dollar','SR',0);
INSERT INTO currencies_en VALUES ('SSP',728,2,'South Sudanese pound','SD',0);
INSERT INTO currencies_en VALUES ('STD',678,2,'São Tomé and Príncipe dobra','ST',0);
INSERT INTO currencies_en VALUES ('SYP',760,2,'Syrian pound','SY',0);
INSERT INTO currencies_en VALUES ('SZL',748,2,'Swazi lilangeni','SZ',0);
INSERT INTO currencies_en VALUES ('THB',764,2,'Thai baht','TH',0);
INSERT INTO currencies_en VALUES ('TJS',972,2,'Tajikistani somoni','TJ',0);
INSERT INTO currencies_en VALUES ('TMT',934,2,'Turkmenistani manat','TM',0);
INSERT INTO currencies_en VALUES ('TND',788,3,'Tunisian dinar','TN',0);
INSERT INTO currencies_en VALUES ('TOP',776,2,'Tongan pa anga','TO',0);
INSERT INTO currencies_en VALUES ('TRY',949,2,'Turkish lira','TR,CY',0);
INSERT INTO currencies_en VALUES ('TTD',780,2,'Trinidad and Tobago dollar','TT',0);
INSERT INTO currencies_en VALUES ('TWD',901,2,'New Taiwan dollar','TW',0);
INSERT INTO currencies_en VALUES ('TZS',834,2,'Tanzanian shilling','TZ',0);
INSERT INTO currencies_en VALUES ('UAH',980,2,'Ukrainian hryvnia','UA',0);
INSERT INTO currencies_en VALUES ('UGX',800,0,'Ugandan shilling','UG',0);
INSERT INTO currencies_en VALUES ('USD',840,2,'United States dollar','AS,BB,BM,OI,VG,AN,EC,SV,GU,HT,MH,FM,MP,PW,PA,PR,TP,TC,US,VI,ZW',0);
INSERT INTO currencies_en VALUES ('USN',997,2,'United States dollar (next day)','US',0);
INSERT INTO currencies_en VALUES ('USS',998,2,'United States dollar (same day)','US',0);
INSERT INTO currencies_en VALUES ('UYI',940,0,'Uruguay Peso en Unidades Indexadas (URUIURUI)','UY',0);
INSERT INTO currencies_en VALUES ('UYU',858,2,'Uruguayan peso','UY',0);
INSERT INTO currencies_en VALUES ('UZS',860,2,'Uzbekistan som','UZ',0);
INSERT INTO currencies_en VALUES ('VEF',937,2,'Venezuelan bolívar','VE',0);
INSERT INTO currencies_en VALUES ('VND',704,0,'Vietnamese dong','VN',0);
INSERT INTO currencies_en VALUES ('VUV',548,0,'Vanuatu vatu','VU',0);
INSERT INTO currencies_en VALUES ('WST',882,2,'Samoan tala','WS',0);
INSERT INTO currencies_en VALUES ('XAF',950,0,'Central African CFA franc','CM,CF,CD,TD,GQ,GA',0);
INSERT INTO currencies_en VALUES ('XAG',961,0,'Troy ounce Silver','',0);
INSERT INTO currencies_en VALUES ('XAU',959,0,'Troy ounce Gold','',0);
INSERT INTO currencies_en VALUES ('XBA',955,0,'European Composite Unit','',0);
INSERT INTO currencies_en VALUES ('XBB',956,0,'European Monetary Unit','',0);
INSERT INTO currencies_en VALUES ('XBC',957,0,'European Unit of Account 9','',0);
INSERT INTO currencies_en VALUES ('XBD',958,0,'European Unit of Account 17','',0);
INSERT INTO currencies_en VALUES ('XCD',951,2,'East Caribbean dollar','AI,AG,DM,GD,MS,KN,LC,VC',0);
INSERT INTO currencies_en VALUES ('XDR',960,0,'Special drawing rights','',0);
INSERT INTO currencies_en VALUES ('XFU',null,0,'UIC franc','',0);
INSERT INTO currencies_en VALUES ('XOF',952,0,'West African CFA franc','BJ,BF,GW,ML,NE,SN,TG',0);
INSERT INTO currencies_en VALUES ('XPD',964,0,'Troy ounce Palladium','',0);
INSERT INTO currencies_en VALUES ('XPF',953,0,'CFP franc','PF,NC,WF',0);
INSERT INTO currencies_en VALUES ('XPT',962,0,'Troy ouncePlatinum','',0);
INSERT INTO currencies_en VALUES ('XTS',963,0,'Code reserved for testing purposes','',0);
INSERT INTO currencies_en VALUES ('XXX',999,0,'No currency','',0);
INSERT INTO currencies_en VALUES ('YER',886,2,'Yemeni rial','YE',0);
INSERT INTO currencies_en VALUES ('ZAR',710,2,'South African rand','ZA',0);
INSERT INTO currencies_en VALUES ('ZMW',967,2,'Zambian kwacha','ZM',0);
INSERT INTO currencies_en VALUES ('ZWL',932,2,'Zimbabwe dollar','ZW',0);
