DROP TABLE countries;
CREATE TABLE countries (
	code char(2) CONSTRAINT country_code PRIMARY KEY ASC,
	country varchar(50) CONSTRAINT country_name UNIQUE,
	language varchar(32),
	charset varchar(32),
	enabled int(1),
	lang_code varchar(5)
);
INSERT INTO countries VALUES ('AD','Andorra','Catalan','iso-8859-1','0','ca');
INSERT INTO countries VALUES ('AE','United Arab Emirates','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AF','Afghanistan','Dari, Pushtu','iso-8859-1','0','');
INSERT INTO countries VALUES ('AG','Antigua and Barbuda','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AI','Anguilla','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AL','Albania','Albanian','iso-8859-1','0','sq');
INSERT INTO countries VALUES ('AM','Armenia','Armenian','iso-8859-1','0','');
INSERT INTO countries VALUES ('AN','Netherlands Antilles','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AO','Angola','Portuguese','iso-8859-1','0','pt');
INSERT INTO countries VALUES ('AQ','Antarctica','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AR','Argentina','Spanish','iso-8859-1','0','sp-ar');
INSERT INTO countries VALUES ('AS','American Samoa','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AT','Austria','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AU','Australia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AW','Aruba','','iso-8859-1','0','');
INSERT INTO countries VALUES ('AZ','Azerbaijan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BA','Bosnia and Herzegowina','Bosnian','iso-8859-1','0','');
INSERT INTO countries VALUES ('BB','Barbados','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BD','Bangladesh','Bengali','iso-8859-1','0','');
INSERT INTO countries VALUES ('BE','Belgium','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BF','Burkina Faso','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BG','Bulgaria','Bulgarian','iso-8859-1','0','bg');
INSERT INTO countries VALUES ('BH','Bahrain','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BI','Burundi','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BJ','Benin','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BM','Bermuda','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BN','Brunei Darussalam','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BO','Bolivia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BR','Brazil','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BS','Bahamas','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BT','Bhutan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BV','Bouvet Island','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BW','Botswana','','iso-8859-1','0','');
INSERT INTO countries VALUES ('BY','Belarus','Belarussian','iso-8859-1','0','be');
INSERT INTO countries VALUES ('BZ','Belize','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CA','Canada','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CC','Cocos (Keeling) Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CD','Congo, Democratic Republic of','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CF','Central African Republic','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CH','Switzerland','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CI','Cote D ivoire', '','iso-8859-1','0','');
INSERT INTO countries VALUES ('CK','Cook Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CL','Chile','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CM','Cameroon','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CN','China','Chinese','iso-8859-1','0','zh-hk');
INSERT INTO countries VALUES ('CO','Colombia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CR','Costa Rica','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CS','Czechoslovakia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CU','Cuba','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CV','Cape Verde','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CX','Christmas Island','','iso-8859-1','0','');
INSERT INTO countries VALUES ('CY','Cyprus','Greek','iso-8859-1','0','el');
INSERT INTO countries VALUES ('CZ','Czech Republic','Czech','iso-8859-1','0','cs');
INSERT INTO countries VALUES ('DE','Germany','German','iso-8859-1','0','de');
INSERT INTO countries VALUES ('DJ','Djibouti','','iso-8859-1','0','');
INSERT INTO countries VALUES ('DK','Denmark','Danish','iso-8859-1','0','da');
INSERT INTO countries VALUES ('DM','Dominica','','iso-8859-1','0','');
INSERT INTO countries VALUES ('DO','Dominican Republic','','iso-8859-1','0','');
INSERT INTO countries VALUES ('DZ','Algeria','Arabic','iso-8859-1','0','ar-dz');
INSERT INTO countries VALUES ('EC','Ecuador','','iso-8859-1','0','');
INSERT INTO countries VALUES ('EE','Estonia','Estonian','iso-8859-1','0','et');
INSERT INTO countries VALUES ('EG','Egypt','','iso-8859-1','0','');
INSERT INTO countries VALUES ('EH','Western Sahara','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ER','Eritrea','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ES','Spain','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ET','Ethiopia','Amharic','iso-8859-1','0','');
INSERT INTO countries VALUES ('FI','Finland','Finnish, Swedish','iso-8859-1','0','fi');
INSERT INTO countries VALUES ('FJ','Fiji','','iso-8859-1','0','');
INSERT INTO countries VALUES ('FK','Falkland Islands (Malvinas)','','iso-8859-1','0','');
INSERT INTO countries VALUES ('FM','Micronesia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('FO','Faroe Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('FR','France','French','iso-8859-1','0','fr');
INSERT INTO countries VALUES ('FX','France, Metropolitan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GA','Gabon','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GB','United Kingdom (Great Britain)','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GD','Grenada','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GE','Georgia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GF','French Guiana','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GH','Ghana','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GI','Gibraltar','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GL','Greenland','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GM','Gambia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GN','Guinea','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GP','Guadeloupe','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GQ','Equatorial Guinea','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GR','Greece','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GT','Guatemala','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GU','Guam','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GW','Guinea-Bissau','','iso-8859-1','0','');
INSERT INTO countries VALUES ('GY','Guyana','','iso-8859-1','0','');
INSERT INTO countries VALUES ('HK','Hong Kong','Mandarin','iso-8859-1','0','');
INSERT INTO countries VALUES ('HM','Heard and McDonald Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('HN','Honduras','','iso-8859-1','0','');
INSERT INTO countries VALUES ('HR','Croatia','Croatian','iso-8859-1','0','hr');
INSERT INTO countries VALUES ('HT','Haiti','Creole','iso-8859-1','0','');
INSERT INTO countries VALUES ('HU','Hungary','Hungarian','iso-8859-1','0','hu');
INSERT INTO countries VALUES ('ID','Indonesia','Indonesian','iso-8859-1','0','in');
INSERT INTO countries VALUES ('IE','Ireland','Irish','iso-8859-1','0','');
INSERT INTO countries VALUES ('IL','Israel','Hebrew','iso-8859-1','0','he');
INSERT INTO countries VALUES ('IN','India','','iso-8859-1','0','');
INSERT INTO countries VALUES ('IO','British Indian Ocean Territory','','iso-8859-1','0','');
INSERT INTO countries VALUES ('IQ','Iraq','','iso-8859-1','0','');
INSERT INTO countries VALUES ('IR','Islamic Republic of Iran','','iso-8859-1','0','');
INSERT INTO countries VALUES ('IS','Iceland','Icelandic','iso-8859-1','0','is');
INSERT INTO countries VALUES ('IT','Italy','Italian','iso-8859-1','0','it');
INSERT INTO countries VALUES ('JM','Jamaica','','iso-8859-1','0','');
INSERT INTO countries VALUES ('JO','Jordan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('JP','Japan','Japanese','iso-8859-1','0','ja');
INSERT INTO countries VALUES ('KE','Kenya','Kiswahili','iso-8859-1','0','');
INSERT INTO countries VALUES ('KG','Kyrgyzstan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KH','Cambodia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KI','Kiribati','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KM','Comoros','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KN','St. Kitts And Nevis','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KP','Korea','Korean','iso-8859-1','0','ko');
INSERT INTO countries VALUES ('KR','Korea, Republic of','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KW','Kuwait','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KY','Cayman Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('KZ','Kazakhstan','Kazakh','iso-8859-1','0','');
INSERT INTO countries VALUES ('LA','Laos','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LB','Lebanon','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LC','Saint Lucia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LI','Liechtenstein','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LK','Sri Lanka','Sinhala','iso-8859-1','0','');
INSERT INTO countries VALUES ('LR','Liberia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LS','Lesotho','Sesotho','iso-8859-1','0','');
INSERT INTO countries VALUES ('LT','Lithuania','Lithuanian','iso-8859-1','0','lt');
INSERT INTO countries VALUES ('LU','Luxembourg','','iso-8859-1','0','');
INSERT INTO countries VALUES ('LV','Latvia','Latvian','iso-8859-1','0','lv');
INSERT INTO countries VALUES ('LY','Libyan Arab Jamahiriya','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MA','Morocco','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MC','Monaco','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MD','Moldova, Republic of','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MG','Madagascar','Malagasy','iso-8859-1','0','');
INSERT INTO countries VALUES ('MH','Marshall Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MK','Macedonia','Macedonian','iso-8859-1','0','mk');
INSERT INTO countries VALUES ('ML','Mali','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MM','Myanmar','Burmese','iso-8859-1','0','');
INSERT INTO countries VALUES ('MN','Mongolia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MO','Macau','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MP','Northern Mariana Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MQ','Martinique','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MR','Mauritania','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MS','Montserrat','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MT','Malta','Maltese','iso-8859-1','0','mt');
INSERT INTO countries VALUES ('MU','Mauritius','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MV','Maldives','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MW','Malawi','','iso-8859-1','0','');
INSERT INTO countries VALUES ('MX','México','Español','iso-8859-1','1','es-mx');
INSERT INTO countries VALUES ('MY','Malaysia','Malay','iso-8859-1','0','mz');
INSERT INTO countries VALUES ('MZ','Mozambique','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NA','Namibia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NC','New Caledonia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NE','Niger','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NF','Norfolk Island','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NG','Nigeria','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NI','Nicaragua','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NL','Netherlands','Dutch','iso-8859-1','0','nl');
INSERT INTO countries VALUES ('NO','Norway','Norwegian','iso-8859-1','0','no');
INSERT INTO countries VALUES ('NP','Nepal','Nepali','iso-8859-1','0','');
INSERT INTO countries VALUES ('NR','Nauru','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NU','Niue','','iso-8859-1','0','');
INSERT INTO countries VALUES ('NZ','New Zealand','','iso-8859-1','0','');
INSERT INTO countries VALUES ('OM','Oman','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PA','Panama','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PE','Peru','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PF','French Polynesia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PG','Papua New Guinea','Pidgin','iso-8859-1','0','');
INSERT INTO countries VALUES ('PH','Philippines','Filipino','iso-8859-1','0','');
INSERT INTO countries VALUES ('PK','Pakistan','Urdu','iso-8859-1','0','ur');
INSERT INTO countries VALUES ('PL','Poland','Polish','iso-8859-1','0','pl');
INSERT INTO countries VALUES ('PM','St. Pierre and Miquelon','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PN','Pitcairn','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PR','Puerto Rico','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PT','Portugal','Portuguese','iso-8859-1','0','pt');
INSERT INTO countries VALUES ('PW','Palau','','iso-8859-1','0','');
INSERT INTO countries VALUES ('PY','Paraguay','','iso-8859-1','0','');
INSERT INTO countries VALUES ('QA','Qatar','','iso-8859-1','0','');
INSERT INTO countries VALUES ('RE','Reunion','','iso-8859-1','0','');
INSERT INTO countries VALUES ('RO','Romania','Romanian','iso-8859-1','0','ro');
INSERT INTO countries VALUES ('RU','Russian Federation','Russian','Windows-1251','0','ru');
INSERT INTO countries VALUES ('RW','Rwanda','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SA','Saudi Arabia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SB','Solomon Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SC','Seychelles','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SD','Sudan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SE','Sweden','Swedish','iso-8859-1','0','sv');
INSERT INTO countries VALUES ('SG','Singapore','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SH','St. Helena','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SI','Slovenia','Slovene','iso-8859-1','0','sl');
INSERT INTO countries VALUES ('SJ','Svalbard and Jan Mayen Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SK','Slovakia','Slovak','iso-8859-1','0','sk');
INSERT INTO countries VALUES ('SL','Sierra Leone','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SM','San Marino','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SN','Senegal','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SO','Somalia','Somali','iso-8859-1','0','');
INSERT INTO countries VALUES ('SR','Suriname','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ST','Sao Tome and Principe','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SV','El Salvador','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SY','Syrian Arab Republic','','iso-8859-1','0','');
INSERT INTO countries VALUES ('SZ','Swaziland','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TC','Turks and Caicos Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TD','Chad','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TF','French Southern Territories','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TG','Togo','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TH','Thailand','Thai','iso-8859-1','0','th');
INSERT INTO countries VALUES ('TJ','Tajikistan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TK','Tokelau','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TM','Turkmenistan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TN','Tunisia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TO','Tonga','Tongan','iso-8859-1','0','');
INSERT INTO countries VALUES ('TP','East Timor','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TR','Turkey','Turkish','iso-8859-1','0','tr');
INSERT INTO countries VALUES ('TT','Trinidad and Tobago','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TV','Tuvalu','Tuvaluan','iso-8859-1','0','');
INSERT INTO countries VALUES ('TW','Taiwan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('TZ','Tanzania, United Republic of','','iso-8859-1','0','');
INSERT INTO countries VALUES ('UA','Ukraine','Ukrainian','iso-8859-1','0','uk');
INSERT INTO countries VALUES ('UG','Uganda','','iso-8859-1','0','');
INSERT INTO countries VALUES ('US','United States','English','iso-8859-1','1','en-us');
INSERT INTO countries VALUES ('UY','Uruguay','','iso-8859-1','0','');
INSERT INTO countries VALUES ('UZ','Uzbekistan','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VA','Vatican City State','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VC','St. Vincent And The Greadines','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VE','Venezuela','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VG','British Virgin Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VI','United States Virgin Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('VN','Viet Nam','Vietnamese','iso-8859-1','0','vi');
INSERT INTO countries VALUES ('VU','Vanuatu','','iso-8859-1','0','');
INSERT INTO countries VALUES ('WF','Wallis And Futuna Islands','','iso-8859-1','0','');
INSERT INTO countries VALUES ('WS','Samoa','','iso-8859-1','0','');
INSERT INTO countries VALUES ('YE','Yemen','','iso-8859-1','0','');
INSERT INTO countries VALUES ('YT','Mayotte','','iso-8859-1','0','');
INSERT INTO countries VALUES ('YU','Yugoslavia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ZA','South Africa','Afrikaans','iso-8859-1','0','af');
INSERT INTO countries VALUES ('ZM','Zambia','','iso-8859-1','0','');
INSERT INTO countries VALUES ('ZW','Zimbabwe','','iso-8859-1','0','');
