@ECHO OFF
CLS
ECHO Buscando base de datos...
DIR ..\..\install\database\sqlite /b/A:D >Files.txt
ECHO Procesando base de datos...
FOR /F "skip=1" %%d in (Files.txt) DO CALL generateSQLiteFile %%d
ECHO Moviendo base de datos...
MOVE /Y *.sq2 ..\php\mekayotl\database\sqlite\data\*.*
ECHO Borrando cache...
DEL /Q *.txt