DROP TABLE cities;
CREATE TABLE cities (
	city varchar(50),
	state_code varchar(5)
);
INSERT INTO cities VALUES ('Aguascalientes','AGS');
INSERT INTO cities VALUES ('Ensenada','BC');
INSERT INTO cities VALUES ('Mexicali','BC');
INSERT INTO cities VALUES ('Tijuana','BC');
INSERT INTO cities VALUES ('Cabo San Lucas','BCS');
INSERT INTO cities VALUES ('San José del Cabo','BCS');
INSERT INTO cities VALUES ('San Francisco de Campeche','CAMP');
INSERT INTO cities VALUES ('Barrancas del Cobre','CHIH');
INSERT INTO cities VALUES ('Chihuahua','CHIH');
INSERT INTO cities VALUES ('Ciudad Juárez','CHIH');
INSERT INTO cities VALUES ('Palenque','CHIS');
INSERT INTO cities VALUES ('Tuxtla Gutiérrez','CHIS');
INSERT INTO cities VALUES ('Ciudad Acuña','COAH');
INSERT INTO cities VALUES ('Monclova','COAH');
INSERT INTO cities VALUES ('Saltillo','COAH');
INSERT INTO cities VALUES ('Torreón','COAH');
INSERT INTO cities VALUES ('Colima','COL');
INSERT INTO cities VALUES ('Isla Navidad','COL');
INSERT INTO cities VALUES ('Manzanillo','COL');
INSERT INTO cities VALUES ('Distrito Federal','DF');
INSERT INTO cities VALUES ('Durango','DGO');
INSERT INTO cities VALUES ('Gómez Palacio','DGO');
INSERT INTO cities VALUES ('Acapulco de Juárez','GRO');
INSERT INTO cities VALUES ('Ixtapa','GRO');
INSERT INTO cities VALUES ('Taxco de Alarcón','GRO');
INSERT INTO cities VALUES ('Celaya','GTO');
INSERT INTO cities VALUES ('Guanajuato','GTO');
INSERT INTO cities VALUES ('Irapuato','GTO');
INSERT INTO cities VALUES ('Leon de los Aldama (León)','GTO');
INSERT INTO cities VALUES ('San miguel de Allende','GTO');
INSERT INTO cities VALUES ('Tula de Allende','HGO');
INSERT INTO cities VALUES ('Barra de Navidad','JAL');
INSERT INTO cities VALUES ('Guadalajara','JAL');
INSERT INTO cities VALUES ('Mascota','JAL');
INSERT INTO cities VALUES ('Mazamitla','JAL');
INSERT INTO cities VALUES ('Melaque','JAL');
INSERT INTO cities VALUES ('Puerto Vallarta','JAL');
INSERT INTO cities VALUES ('Tenacatita','JAL');
INSERT INTO cities VALUES ('Tepatitlán de Morelos','JAL');
INSERT INTO cities VALUES ('Toluca de Lerdo','MEX');
INSERT INTO cities VALUES ('Morelia','MICH');
INSERT INTO cities VALUES ('Patzcuaro','MICH');
INSERT INTO cities VALUES ('Cuernavaca','MRO');
INSERT INTO cities VALUES ('Bucerias','NAY');
INSERT INTO cities VALUES ('Nuevo Vallarta','NAY');
INSERT INTO cities VALUES ('Punta de Mita','NAY');
INSERT INTO cities VALUES ('Rincón de Guayabitos','NAY');
INSERT INTO cities VALUES ('Santa María del Oro','NAY');
INSERT INTO cities VALUES ('Apodaca','NL');
INSERT INTO cities VALUES ('Monterrey','NL');
INSERT INTO cities VALUES ('Oaxaca (Oaxaca de Juárez)','OAX');
INSERT INTO cities VALUES ('Puerto Escondido','OAX');
INSERT INTO cities VALUES ('Puebla (Heroica Puebla)','PUE');
INSERT INTO cities VALUES ('Cancún','QR');
INSERT INTO cities VALUES ('Cozumel','QR');
INSERT INTO cities VALUES ('Querétaro','QRO');
INSERT INTO cities VALUES ('Los Mochis','SIN');
INSERT INTO cities VALUES ('Mazatlán','SIN');
INSERT INTO cities VALUES ('Ciudad Valles','SLP');
INSERT INTO cities VALUES ('San Luis Potosí','SLP');
INSERT INTO cities VALUES ('Ciudad Obregón','SON');
INSERT INTO cities VALUES ('Navojoa','SON');
INSERT INTO cities VALUES ('Puerto Peñasco','SON');
INSERT INTO cities VALUES ('San Carlos Nuevo Guaymas','SON');
INSERT INTO cities VALUES ('Villahermosa','TAB');
INSERT INTO cities VALUES ('Altamira','TAMS');
INSERT INTO cities VALUES ('Ciudad Madero','TAMS');
INSERT INTO cities VALUES ('Ciudad Victoria','TAMS');
INSERT INTO cities VALUES ('Colinas Huatulco (ixtapa)','TAMS');
INSERT INTO cities VALUES ('Huatulco','TAMS');
INSERT INTO cities VALUES ('Matamoros (Heroica Matamoros)','TAMS');
INSERT INTO cities VALUES ('Nuevo Laredo','TAMS');
INSERT INTO cities VALUES ('Reynosa (Ciudad Reynosa)','TAMS');
INSERT INTO cities VALUES ('Tampico','TAMS');
INSERT INTO cities VALUES ('Tlaxcala','TLAX');
INSERT INTO cities VALUES ('Boca del Rio','VER');
INSERT INTO cities VALUES ('Coatzacoalcos','VER');
INSERT INTO cities VALUES ('Poza Rica (Poza Rica de Hidalgo)','VER');
INSERT INTO cities VALUES ('San Rafael','VER');
INSERT INTO cities VALUES ('Veracruz','VER');
INSERT INTO cities VALUES ('Xalapa Enríquez','VER');
INSERT INTO cities VALUES ('Chichen-itza','YUC');
INSERT INTO cities VALUES ('Mérida','YUC');
INSERT INTO cities VALUES ('Uxmal','YUC');
INSERT INTO cities VALUES ('Zacatecas','ZAC');
